it680vizapp/cms/routes.py
from flask import Blueprint
from flask import Flask, render_template
from flask import Flask, render_template, flash, redirect, url_for, g, session, logging, request
from .form import RegisterForm, TransactionForm, EditUserForm
from _mysql import escape_string as thwart
from functools import wraps
from passlib.hash import sha256_crypt
from it680vizapp import mysql
from flask import current_app


mod = Blueprint('cms', __name__, template_folder='templates', static_url_path='/cms/static', static_folder='./static')


#User Login process and conditional routes to user login page and dashboard
@mod.route('/admin', methods = ['GET','POST'])
def admin():
	if 'logged_in' in session:
		return redirect(url_for('cms.dashboard'))

	elif request.method == 'POST':
		#Get data from login form
		#name = request.form['name']
		username = request.form['username']
		form_pass = request.form['password']

		#login cursor
		cur = mysql.connection.cursor()
		#Get username
		result = cur.execute("select u.name, u.username, u.super_user, u.password from user u where u.username = %s", [username])
		user_data = cur.fetchone()
		
		if result > 0:
			#get stored hash
			users_fullname = user_data['name']
			user_name = user_data['username']
			user_pass = user_data['password']
			super_user = user_data['super_user']

			#Compare pass
			if user_name:				
				if sha256_crypt.verify(form_pass, user_pass) == False:
					flash('password do not match!', 'danger')
				# elif auth_data not in ['Admin', 'admin']:
				# 	flash('Access denied, not sufficient privilege!', 'danger')
				# 	return render_template('site/login.html')
				elif super_user:
					# if username = user_name
					session['logged_in'] = True
					session['username'] = username
					session['super_user'] = super_user

					flash('Welcome Admin' , 'success')
					return render_template('cms/dashboard.html', data=user_data)
					# return render_template('index.html')
					cur.close()
					mysql.connection.close()
			else:
				error = '.'
				return render_template('cms/login.html', error=error)				
		else:
			error = 'User not found.'
			return render_template('cms/login.html', error=error)
	return render_template('cms/login.html')



#Wrap session for logged in access to pages
def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
	    if 'logged_in' in session:
	    	return f(*args, **kwargs)
	    else:
	    	flash('Not logged in, Please login first.','danger')
	    	return redirect(url_for('cms.admin'))
    return wrap


def roles_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        user = session['username']
        cur = mysql.connection.cursor()
        #Get username
        result = cur.execute("select super_user from user where username=%s", [user])
        user_data = cur.fetchone()

        user_auth = user_data['super_user']

        if user_auth > 0:
            return func(*args, **kwargs)
        else:
            flash('Access denied', 'danger')
            return redirect(url_for('site.login'))
    return wrapper



#Admin dashboard route
@mod.route('/admin/dashboard')
@login_required
@roles_required
def dashboard():
	return render_template('cms/dashboard.html')

#Clear admin session
@mod.route('/admin/logout')
def logout():
	session.clear()
	flash('You are logged out', 'success')
	return redirect(url_for('cms.admin'))

#route to view all users -- this is working
@mod.route('/admin/viewusers')
@login_required
@roles_required
def viewusers():
	cur = mysql.connection.cursor()
	user_result = cur.execute("SELECT * FROM user")
	users_data = cur.fetchall()

	if user_result > 0:
		msg = 'table data'
		return render_template('cms/show_users.html', data=users_data)
	else:
		msg = 'No user found.'
		return render_template('cms/show_users.html', msg=msg)

	mysql.connection.commit()
	#close conn
	cur.close()
	mysql.connection.close()


@mod.route('/admin/editrole/<string:user_id>', methods=['GET', 'POST'])
@login_required
@roles_required
def editrole(user_id):
	cur = mysql.connection.cursor()
	cur_2 = mysql.connection.cursor()
	user_result = cur.execute("SELECT * FROM user where user_id = %s", [user_id])
	#user_auth_result = cur_2.execute("SELECT * FROM authorities where user_id = %s", [user_id])
	users_data = cur.fetchone()
	#user_auth = cur_2.fetchone()

	mysql.connection.commit()

	form = EditUserForm(request.form)

	form.enabled.data = users_data['enabled']
	#form.authority.data = user_auth['authority']

	return render_template('cms/edituser.html', u_data=users_data)#, u_auth=user_auth)

#Change role of user -- not working yet
@mod.route('/admin/edituser/<string:user_id>', methods=['GET', 'POST'])
@login_required
@roles_required
def edituser(user_id):
	cur = mysql.connection.cursor()
	cur_2 = mysql.connection.cursor()
	user_result = cur.execute("SELECT * FROM user where user_id = %s", [user_id])
	#user_auth_result = cur_2.execute("SELECT * FROM authorities where user_id = %s", [user_id])
	users_data = cur.fetchone()
	#user_auth = cur_2.fetchone()


	mysql.connection.commit()

	form = EditUserForm(request.form)
	form.name.data = users_data['name']
	form.username.data = users_data['username']
	form.email.data = users_data['email']
	#form.authority.data = user_auth['authority']

	
	if request.method == 'POST' and form.validate():
		stat = request.form['enabled']
		if stat == 'active':
			enabled = 1
		elif stat == 'inactive':
			enabled = 0
				
		cur = mysql.connection.cursor()

		query_1 = ''' UPDATE user SET enabled = %s WHERE user_id = %s '''
		cur.execute(query_1, ([enabled], [user_id]))

		query_3 = ''' SELECT enabled from users_v2 where user_id = %s '''
		cur.execute(query_3, ([user_id]))

		enabled_new = cur.fetchone()

		mysql.connection.commit()

		# request.form['authority'] = authority
		#close conn
		cur.close()

		flash('Update successful', 'success')
		# return redirect(url_for('cms.viewusers'))
		return render_template('cms/edituser.html', form=form, status=enabled_new)
	return render_template('cms/edituser.html', form=form)


#Delete user -- this is working
@mod.route('/admin/deleteuser/<string:user_id>', methods=['POST'])
@login_required
@roles_required
def deleteuser(user_id):
	#app.logger.info([user_id])
	
	cur = mysql.connection.cursor()
	#cur.execute("DELETE FROM authorities WHERE user_id=%s", [user_id])
	#cur.execute("SELECT user_id, authority from authorities where user_id=%s", [user_id])
	#auth_table = cur.fetchone()
	#mysql.connection.commit()

	cur.execute("DELETE FROM user WHERE user_id=%s", [user_id])
	mysql.connection.commit()


	
	cur.execute("SELECT user_id from user where user_id = %s", [user_id])
	test = cur.fetchone()
	if test is None:
		flash("User is Deleted", 'success')
		return redirect(url_for('cms.viewusers'))
	else:
		flash("Query is not working", 'danger')
		return redirect(url_for('cms.viewusers'))

	mysql.connection.commit()
	#close conn
	cur.close()
	mysql.connection.close()


# @mod.route('/admin/edituser/<int:user_id>')
# @login_required
# def edituser(user_id):
# 	cur = mysql.connection.cursor()
# 	user_result = cur.execute("SELECT * FROM users_v2 u join authorities a on u.user_id = a.user_id having user_id = %s", ([user_id]))
# 	users_data = cur.fetchone()

# 	if user_result > 0:
# 		return render_template('cms/edituser.html', data=users_data, id=)
# 	else:
# 		msg = 'No user found.'
# 		return render_template('cms/show_users.html', msg=msg)

# 	mysql.connection.commit()
# 	#close conn
# 	cur.close()
# 	mysql.connection.close()

it680vizapp/cms/templates/cms/dashboard.html
{% extends 'cms/layout.html' %}

{% block body %}
	<div class="row">
	  <div class="col-sm-2">
	    <div class="sidebar-nav">
	      <div class="navbar navbar-default" role="navigation">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <span class="visible-xs navbar-brand">Sidebar menu</span>
	        </div>


	        <div class="navbar-collapse collapse sidebar-navbar-collapse">
	          <ul class="nav navbar-nav">
	          	<li><a id='dash_li' href="#">Dashboard</a></li>
	          	<li><a id='users_li' href="#">Users</a></li>
	            <li><a id='trans_li' href="#">Transactions</a></li>
	            <li><a href="#">Contact</a></li>
	          </ul>
	        </div><!--/.nav-collapse -->
	      </div>
	    </div>
	  </div>
		  <div class="col-sm-10" id="content">
		    <div class="container">
		    	<h1 id="msg">Welcome to your dashboard.</h1>
		    </div>
		  </div>
	</div>

{% endblock %}

it680vizapp/cms/templates/cms/edituser.html
{% extends 'cms/layout.html' %}

{% block body %}
	<h1>Update user</h1>
	{% from "cms/includes/_formhelpers.html" import render_field %}
	
	<form method="POST" action="">
		<div class="form-group">
			{{render_field(form.name, class_="form-control", disabled=True)}}
		</div>
		<div class="form-group">
			{{render_field(form.username, class_="form-control", disabled=True)}}
		</div>
		<div class="form-group">
			{{render_field(form.email, class_="form-control", disabled=True)}}
		</div>
		<!-- <div class="form-group">
			{{render_field(form.authority, class_="form-control")}}
		</div> -->
		<div class="form-group">
			<label>Status</label>
			<select class="form-control" name="enabled">
			  <option value="" disabled selected>Change status</option>	
			  <option value="active">Active</option>
			  <option value="inactive">Inactive</option>
			</select>							
		</div>
		<p><input type="submit" class="btn btn-primary" value="submit"></p>
	</form>

{% endblock %}

it680vizapp/cms/templates/cms/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Mankato Expenses</title>
	<link rel="stylesheet" href=" {{ url_for('cms.static', filename='css/style.css') }}">
	<link rel="stylesheet" href=" {{ url_for('cms.static', filename='css/bootstrap.css') }}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<script src="{{ url_for('cms.static', filename='js/jquery.min.js') }}"></script>
</head>
<body>
	{% include 'cms/includes/_navbar.html' %}
	<div class="container">

		{% include 'cms/includes/_messages.html' %}
		
		{% block body %}

		{% endblock %}
	</div>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
	<script src="{{ url_for('cms.static', filename='js/main.js') }}"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</body>
</html>

it680vizapp/cms/templates/cms/login.html
{% extends 'cms/layout.html' %}

{% block body %}
	{% from "site/includes/_formhelpers.html" import render_field %}
<div class="container">
	<div class="row">
	    <div class="col-md-offset-3 col-md-6">
			<h1>Admin Login Panel</h1>
			<form method="POST" action="" class="login_form">
				<div class="form-group">
					<label>Username</label>
					<input type="text" name="username" class="form-control" value="{{request.form.username}}">
				</div>
				<div class="form-group">
					<label>Password</label>
					<input type="password" name="password" class="form-control" value="{{request.form.password}}">
				</div>
				<p><input type="submit" class="btn btn-success" value="submit"></p>
			</form>
		</div>
	</div>
</div>
{% endblock %}

it680vizapp/cms/templates/cms/show_users.html
{% extends 'cms/layout.html' %}

{% block body %}
	<div class="container">
	   <table class="table table-bordered" id='show_users'>
	     <thead>
	       <tr>
	         <th>User ID</th>
	         <th>Name</th>
	         <th>Email</th>
	         <th>Username</th>
	         <th>Role</th>
	         <th>Registered Date</th>
	         <th>Status</th>
	         <th>Action</th>
	       </tr>
	     </thead>
	     <tbody>
	     	{% for item in data %}
	       <tr>
	         <td>{{ item.user_id }}</td>
	         <td>{{ item.name }}</a></td>
	         <td>{{ item.email }}</td>
	         <td>{{ item.username }}</td>
	         <td>{{ item.authority }}</td>
	         <td>{{ item.register_date }}</td>
	         {% if item.enabled == 1 %}
	         	<td>Active</td>
	         {% else %}
	         	<td>Inactive</td>
	         {% endif %}
	         <td class="user_btn">
	         	<a href="/admin/edituser/{{item.user_id}}" class="btn btn-info btn-xs pull-left" id="user_edit">Edit</a>
		         <form action="{{ url_for('cms.deleteuser', user_id=item.user_id) }}" method="POST">
		         	<input type="hidden" name="_method" value="DELETE">
		         	<input type="submit" value="Delete" class="btn btn-warning btn-xs" id="user_del">
		         </form>
	     	</td>
	       </tr>
	       
	       {% endfor %}

	     </tbody>
	   </table>
	</div>

{% endblock %}

it680vizapp/cms/templates/cms/test.html
<p id="source">This is test page.</p>