it680vizapp/site/routes.py
from flask import Flask, Blueprint, jsonify
from flask import Flask, render_template, flash, redirect, url_for, g, session, logging, request
from passlib.hash import sha256_crypt
from functools import wraps
from sqlalchemy.orm import sessionmaker
from jinja2 import Environment, PackageLoader, select_autoescape
from .form import RegisterForm, TransactionForm, EditTransForm, EmailForm, PasswordForm
from it680vizapp import mysql, mail, serialize
from flask_mail import Message
#from mysql import escape_string as thwart
from flask import current_app
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
import pandas as pd
import json
import datetime as dt
from flask_paginate import Pagination, get_page_parameter


#from wapy.api import Wapy
#from walmart_api_client import WalmartApiClient
import pandas.io.sql as psql
from it680vizapp.group.routes import get_users_id

from itsdangerous import URLSafeTimedSerializer, SignatureExpired

#Site blue print
mod = Blueprint('site', __name__, template_folder='templates', static_url_path='/site/static', static_folder='./static')
default_breadcrumb_root(mod, '.')


def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
        	flash('Not logged in, Please login first.','danger')
        	return redirect(url_for('site.login'))
    return wrap




#Index route 
@mod.route('/')
# @register_breadcrumb(mod, '.', 'Home')
def index():
	return render_template('site/index.html')

#Site homepage route
@mod.route('/home')
@register_breadcrumb(mod, '.', 'Home', order=0)
def home():
	return render_template('site/index.html')


#Site about page route
@mod.route('/about')
@register_breadcrumb(mod, '.about', 'About', order=5)
def about():
	return render_template('site/about.html')

#Site contact page route
@mod.route('/contact')
# @register_breadcrumb(mod, '.', 'Contact')
def contact():
	return render_template('site/contact.html')

@mod.route('/viz')
def viz():
	return render_template('site/viz.html')


@mod.route('/getdata')
@login_required
def getdata():
	conn = mysql.connection
	cur = mysql.connection.cursor()
	group_id = session['group_id']
	
	query_trans = ''' SELECT sum(ut.share_amount) as amount, t.item
					FROM user_transaction ut
					join transaction t on t.transaction_id = ut.transaction_id
					where t.group_id = %s
					group by t.item
					order by t.item '''

	cur.execute(query_trans, ([group_id]))
	result = cur.fetchall()
	cur.close()
	return jsonify(result)

@mod.route('/get_user_chart_data')
@login_required
def get_user_chart_data():
	conn = mysql.connection
	cur = mysql.connection.cursor()
	group_id = session['group_id']
	
	query_trans = ''' SELECT  u.fname as name, u.user_id, sum(ut.share_amount) as amount
					FROM user u
					join user_transaction ut on ut.user_id = u.user_id
					join transaction t on t.transaction_id = ut.transaction_id
					where t.group_id = %s
					group by u.fname
					order by u.fname '''
	cur.execute(query_trans, ([group_id]))
	result = cur.fetchall()
	cur.close()
	return jsonify(result)

@mod.route('/get_user_chart_data2', methods=['GET', 'POST'])
@login_required
def get_user_chart_data2():
	if request.method == 'POST':
		user_id = request.form['user']
		conn = mysql.connection
		cur = mysql.connection.cursor()
		group_id = session['group_id']
		
		query_trans = ''' SELECT sum(ut.share_amount) as amount, t.item
					FROM user_transaction ut
					join transaction t on t.transaction_id = ut.transaction_id
					where t.group_id = %s and ut.user_id = %s
					group by t.item
					order by t.item '''
		cur.execute(query_trans, ([group_id, user_id]))
		result = cur.fetchall()
		current_app.logger.info(result)
		cur.close()
		return jsonify(result)


@mod.route('/lineChart', methods=['GET', 'POST'])
@login_required
def lineChart():
	if request.method == 'POST':
		user_id = request.form['user']
		conn = mysql.connection
		cur = mysql.connection.cursor()
		group_id = session['group_id']
		
		query_trans = ''' SELECT  u.fname as name, t.manual_date as date, ut.share_amount as amount
						FROM user u
						join user_transaction ut on ut.user_id = u.user_id
						join transaction t on t.transaction_id = ut.transaction_id
						where t.group_id = %s and ut.user_id = %s
						order by t.manual_date
						'''

		cur.execute(query_trans, ([group_id, user_id]))
		result = cur.fetchall()

		format_data = []
		for item in result:
			name = item['name']
			date = item['date'].strftime('%Y-%m-%d %H:%M')
			amount = item['amount']
			format_data.append({'name':name, 'date': date, 'amount':amount})
		current_app.logger.info(format_data)
		cur.close()
		return jsonify(format_data)

############### BELOW ARE CODE FOR USER AUTH, EXPENSE MANAGEMENT ########################

#Wrap session for logged in access to pages


#wrapper for setting role based access for site
# def roles_required(func):
#     @wraps(func)
#     def wrapper(*args, **kwargs):
#         user = session['username']
#         cur = mysql.connection.cursor()
#         #Get username
#         role_query_statement = ''' select u.name, u.username, g.group_name, g.group_id, u.password
#         						 from user u join user_group g on g.user_id = u.user_id 
#         						 having u.username = %s '''

#         result = cur.execute(role_query_statement, [user])
        
#         user_data = cur.fetchone()
#         user_auth = user_data['authority']
#         if user_auth in ['Admin', 'admin', 'member']:
#             return func(*args, **kwargs)
#         else:
#             flash('You do not have access to content of this page, redirected to dashboard', 'danger')
#             return redirect(url_for('site.login'))
#     return wrapper




@mod.route('/register', methods= ['GET', 'POST'])
# @register_breadcrumb(mod, '.', 'Signup')
@register_breadcrumb(mod, '.register', 'Signup')
def register():
	form = RegisterForm(request.form)
	if request.method == 'POST' and form.validate():
		fname = form.fname.data.strip()
		lname = form.lname.data.strip()
		email = form.email.data.strip().lower()
		username = form.username.data.strip().lower()
		password = sha256_crypt.encrypt(str(form.password.data))
		enabled = False

		name = fname + ' ' + lname 

		#create a cursor
		cur = mysql.connection.cursor()

		#query to check if user already exists
		reg_query_username = ''' select username from user where username = %s '''
		cur.execute(reg_query_username, ([username]))

		existing_user = cur.fetchone()
		current_app.logger.info(existing_user)
		#logic to check if user already exists, if not, the insert logics will execute
		if existing_user is None:
			register_insert_query = ''' INSERT INTO user (name, fname, lname, email, username, password, enabled)
										 VALUES(%s, %s, %s, %s, %s, %s, %s) '''
			cur.execute(register_insert_query, (name, fname, lname, email, username, password, enabled))
			mysql.connection.commit()

			enabled_username_query = ''' select username, enabled from user where username = %s '''
			cur.execute(enabled_username_query, ([username]))

			user_data = cur.fetchone()
			enabled_fetch = user_data['enabled']

			if enabled_fetch == 0:
				token = serialize.dumps(email, salt='My-Token')
				current_app.logger.info(token)

				#prepare email msg
				email_msg = Message('Confirm Email', sender='gupta.niraz@gmail.com', recipients=[email])
				link = url_for('site.confirm_email', token=token, _external=True)

				email_msg.body = 'Your link is {}'.format(link)
				mail.send(email_msg)

				flash('Resistration Successful. Please check your email for activation.', 'success')
				return render_template('site/index.html', data=token)
			#redirect(url_for('site.index'))

			#close cursor
			cur.close()
		else:
			flash('User already exits!', 'danger')
	
	# mysql.connection.close()
	return render_template('site/register.html', form=form)


@mod.route('/confirm_email/<token>')
def confirm_email(token):
	try:
		email = serialize.loads(token, salt = 'My-Token', max_age=86400)
	except SignatureExpired:
		return '<h1>The token has expired!</h1>'
	# return '<h1>The token works!</h1>'
	cur = mysql.connection.cursor()
	first_query = ''' SELECT username, enabled from user where email = %s '''
	cur.execute(first_query, ([email]))
	user_data = cur.fetchone()
	user_status = user_data['enabled']
	
	user_name = user_data['username']
	current_app.logger.info(user_status)
	current_app.logger.info(user_name)

	if user_status == True:
		flash('Already activated', 'success')
		session['logged_in'] = True
		session['username'] = user_name
		return redirect(url_for('site.dashboard'))
	else:

		query = '''UPDATE user SET enabled = %s WHERE email = %s'''
		cur.execute(query, (True, [email]))
		mysql.connection.commit()

		flash('Account activated', 'success')
		session['logged_in'] = True
		session['username'] = user_name
	return redirect(url_for('site.dashboard'))

@mod.route('/reset', methods= ['GET', 'POST'])
def password_reset():
	form = EmailForm(request.form)
	if form.validate():
		email = form.email.data.strip()

		cur = mysql.connection.cursor()
		query = '''SELECT * from user WHERE email=%s'''
		cur.execute(query, [email])
		user = cur.fetchone()

		token = serialize.dumps(email, salt='recover_password_key_token')
		current_app.logger.info(token)

		#prepare email msg
		email_msg = Message('Password reset requested', sender='gupta.niraz@gmail.com', recipients=[email])
		link = url_for('site.password_reset_token', token=token, _external=True)

		email_msg.body = 'Please click on the link to change your password {}'.format(link)
		mail.send(email_msg)

		msg = 'A link for password change request has been sent to your Inbox.'
		return render_template('site/index.html', msg=msg)

	return render_template('site/password_reset.html', form=form)


@mod.route('/reset/<token>', methods=["GET", "POST"])
def password_reset_token(token):
	try:

it680vizapp/site/templates/site/about.html
{% extends 'site/layout.html' %}

{% block body %}

	<h1 class="my-4">About Us
	        <small>It's Nice to Meet You!</small>
	      </h1>
	     
	      <!-- Team Members Row -->
	      <div class="row">
	        <div class="col-lg-12">
	        	<p>This app is powered by Python 3.6. We have use the Flask framework for development, CSS, HTML and Javascript for the front-end and client-side processing. And, mysql database for the backend.</p>
	          <h2 class="my-4">Members of 306 Family</h2>
	        </div>
	        <div class="col-lg-4 col-sm-6 text-center mb-4">
	          <img class="image_frame" src="{{ url_for('site.static', filename='img/sonika.jpg') }}" width="150" height="150" alt="">
	          <h3>Sonika Shrestha
	            <small>Family Member</small>
	          </h3>
	          <p>Member of the app for now until the proper role is defined.</p>
	        </div>

	        <div class="col-lg-4 col-sm-6 text-center mb-4">
	          <img class="image_frame" src="{{ url_for('site.static', filename='img/anuj.jpg') }}" width="150" height="150" alt="">
	          <h3>Anuj Bhandari
	            <small>Family Member</small>
	          </h3>
	          <p>Member of the app for now until the proper role is defined.</p>
	        </div>
	       <div class="col-lg-4 col-sm-6 text-center mb-4">
	         <img class="image_frame" src="{{ url_for('site.static', filename='img/suhan.jpg') }}" width="150" height="150" alt="">
	         <h3>Suhan Budhathoki
	           <small>Family Member</small>
	         </h3>
	         <p>Member of the app for now until the proper role is defined.</p>
	       </div>
	       <div class="col-lg-4 col-sm-6 text-center mb-4">
	         <img class="image_frame" src="{{ url_for('site.static', filename='img/bishal.jpg') }}" width="150" height="150" alt="">
	         <h3>Bishal Pandey
	           <small>Family Member</small>
	         </h3>
	         <p>Member of the app for now until the proper role is defined.</p>
	       </div>
	       <div class="col-lg-4 col-sm-6 text-center mb-4">
	         <img class="image_frame" src="{{ url_for('site.static', filename='img/niraj.jpg') }}" width="150" height="150" alt="">
	         <h3>Niraj Gupta
	           <small>Family member and Admin</small>
	         </h3>
	         <p>Developer of the application.</p>
	       </div>
	       <div class="col-lg-4 col-sm-6 text-center mb-4">
	         <img class="image_frame" src="{{ url_for('site.static', filename='img/prashant.jpg') }}" width="150" height="150" alt="">
	         <h3>Prashant Karki
	           <small>Family Member</small>
	         </h3>
	         <p>Member of the app for now until the proper role is defined.</p>
	       </div>

	    </div>
	    <!-- /.container -->

	    <!-- Footer -->
	    <footer class="py-5 bg-dark">
	        <p class="m-0 text-center text-white">Copyright &copy; MankatoExpenses 2017</p>
	      <!-- /.container -->
	    </footer>

{% endblock %}

it680vizapp/site/templates/site/contact.html
{% extends 'site/layout.html' %}

{% block body %}
	<h2>Page under construction.</h2>
{% endblock %}

it680vizapp/site/templates/site/dashboard.html
{% extends 'site/layout.html' %}

{% block body %}

<div class="col-sm-2 sidenav">
		{% include 'site/includes/_vnavbar.html' %}
	  </div>

<div class="col-sm-8 text-left"> 
	<div class="w3-container w3-teal">
		<div class="col-md-9">
			<h1>Dashboard</h1>
		</div>
		</div>

		<table class="w3-table-all w3-card">
			<tbody>
			<tr>
			{% if result.total.total_bal %}
				<td><p class="tran_view_text">Total Paid</p><p class="tran_view_val">${{result.total.total_bal}}</p></td>
			{% else %}
			<td><p class="tran_view_text">Total Paid</p><p class="tran_view_val">$0</p></td>
			{% endif %}
			{% if result.lent.lent_bal %}
				<td><p class="tran_view_text">Total lent</p><p class="tran_view_val">${{result.lent.lent_bal|abs}}</p></td>
			{% else %}
			<td><p class="tran_view_text">Total lent</p><p class="tran_view_val">$0</p></td>
			{% endif %}
			{% if result.expense.shr_amount %}
				<td><p class="tran_view_text">Spent</p><p class="tran_view_val">${{result.expense.shr_amount}}</p></td>
				{% else %}
				<td><p class="tran_view_text">Spent</p><p class="tran_view_val">$0</p></td>
				{% endif %}
			</tr>

			</tbody>
		</table>
</div>
		
{% endblock %}

it680vizapp/site/templates/site/edit_transaction.html
{% extends 'site/layout.html' %}

{% block body %}
	<script type="text/javascript" src="{{ url_for('site.static', filename='js/main.js') }}"></script>
	<div class="col-sm-2 sidenav">
			{% include 'site/includes/_vnavbar.html' %}
		</div>

		<div class="col-sm-8 text-left"> 
			<div class="w3-container w3-teal">
				<h3>Edit Transaction</h3>
			</div>
			</br>
				{% from "site/includes/_formhelpers.html" import render_field %}
				<form method="POST" action="" name="thisForm" id="edit_transaction_form" onsubmit="return validateForm2()">
					
						<div class="form-group">
							{{render_field(form.manual_date, class_="form-control")}}
						</div>
						<div class="form-group">
							{{render_field(form.item, class_="form-control")}}
						</div>
					
						<!-- <div class="form-group" disabled>
							{{render_field(form.amount, class_="form-control")}}
						</div> -->

						<div class="form-group">
							{{render_field(form.description, class_="form-control")}}
						</div>
						<div class="form-group">
							<label>Status</label>
							<select class="form-control" name="status">
							  <option value="" disabled selected>Select your option</option>	
							  <option value="unpaid">Unpaid</option>
							  <option value="paid">Paid</option>
							  <option value="pending">Pending</option>
							</select>							
						</div>
						<input type="submit" class="btn btn-success" value="submit">			
					</div>		
	{% endblock %}

it680vizapp/site/templates/site/index.html
{% extends 'site/layout.html' %}

{% block body %}
<div class="index_image">
  
	  <div class="jumbotron text-center">	  
	    <h1>BillsTracker</h1>
	    <p> This app is designed and developed as part of IT 680 Software Engineering Project. The idea behind this app is to create an interface where people
          can register, create or join groups to split and keep track of their bills.</p>
          <img class="image_frame" src="{{ url_for('site.static', filename='img/billsTracker.jpg') }}" width="400" height="400" alt="">
    </div>
  </div>
  

  <!-- Footer -->
  <!-- <footer class="py-5 bg-dark">
      <p class="m-0 text-center text-white">Copyright &copy; MankatoExpenses 2017</p>
    /.container 
  </footer> -->


{% endblock %}

it680vizapp/site/templates/site/login.html
{% extends 'site/layout.html' %}

{% block body %}
	

	<div class="col-md-offset-3 col-md-6">	
		{% from "site/includes/_formhelpers.html" import render_field %}		
		<h1>Login</h1>
		<form method="POST" action="" name="loginform" onsubmit="return validate()">
			<div class="form-group">
				<label>Username</label>
				<input type="text" name="username" id="form_css1" class="form-control" placeholder="Username" value="{{request.form.username}}">
				<b id="useralert"></b>
			</div>
			<div class="form-group">
				<label>Password</label>
				<input type="password" name="password" id="form_css2" class="form-control" placeholder="Password" value="{{request.form.password}}">
				<b id="passalert"></b>
			</div>
			<p><input type="submit" class="btn btn-success" value="submit" ></p>
		</form>
		<p class="forgot_pass"><a href="{{ url_for('site.password_reset') }}">Forgot Password</a></p>
	</div>

{% endblock %}

it680vizapp/site/templates/site/pass_reset_token.html
{% extends "site/layout.html" %}
 
{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">			
			<h1>Set New Password</h1>
			{% from "site/includes/_formhelpers.html" import render_field %}
			<form action="" method="POST">
				<div class="form-group">
					{{render_field(form.password, class_="form-control")}}
				</div>
				<div class="form-group">
					{{render_field(form.confirm, class_="form-control")}}
				</div>
				
				{{ form.csrf_token }}
				<p><input type="submit" class="btn btn-success" value="submit" ></p>
			</form>
		</div>
	</div>
</div>
{% endblock %}

it680vizapp/site/templates/site/password_reset.html
{% extends "site/layout.html" %}
 
{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-offset-3 col-md-6">			
			<h2>Password reset</h2>
			{% from "site/includes/_formhelpers.html" import render_field %}
			<form action="" method="POST">
				<div class="form-group">
					{{render_field(form.email, class_="form-control")}}
				</div>
				{{ form.csrf_token }}
				<p><input type="submit" class="btn btn-success" value="submit" ></p>
			</form>
		</div>
	</div>
</div>
{% endblock %}

it680vizapp/site/templates/site/register.html
{% extends 'site/layout.html' %}

{% block body %}
<!-- <link rel="stylesheet" type="text/css" href="{{ url_for('site.static', filename='css/stylesheet.css') }}"> -->

<div class="col-md-offset-3 col-md-6 ">	
	<h1>Signup</h1>
	{% from "site/includes/_formhelpers.html" import render_field %}
	<form method="POST" action="">
		
		<div class="form-group">
			{{render_field(form.fname, class_="form-control")}}
		</div>
		<div class="form-group">
			{{render_field(form.lname, class_="form-control")}}
		</div>
		<div class="form-group">
			{{render_field(form.email, class_="form-control")}}
		</div>
		<div class="form-group">
			{{render_field(form.username, class_="form-control")}}
		</div>
		<div class="form-group">
			{{render_field(form.password, class_="form-control")}}
		</div>
		<div class="form-group">
			{{render_field(form.confirm, class_="form-control")}}
		</div>
		<p><input type="submit" class="btn btn-success" value="submit"></p>
	</form>

</div>


	
{% endblock %}

{% block footer %}
	<footer class="py-5 bg-dark">
      <p class="m-0 text-center text-white">Copyright &copy; MankatoExpenses 2017</p>
    <!-- /.container -->
  </footer>
{% endblock %}

it680vizapp/site/templates/site/transaction_form.html
{% extends 'site/layout.html' %}

{% block body %}
	<script type="text/javascript" src="{{ url_for('site.static', filename='js/main.js') }}"></script>
	<div class="col-sm-2 sidenav">
			{% include 'site/includes/_vnavbar.html' %}
		</div>

		<div class="col-sm-8 text-left"> 
			<div class="w3-container w3-teal">
				<h3>New Transaction</h3>
			</div>
			</br>
				{% from "site/includes/_formhelpers.html" import render_field %}
				<form method="POST" action="" name="thisForm" id="transaction_form" onsubmit="return validateForm()">
					
						<div class="form-group">
							{{render_field(form.manual_date, class_="form-control")}}
						</div>
						<div class="form-group">
							{{render_field(form.item, class_="form-control")}}
						</div>
					
						<div class="form-group">
							{{render_field(form.amount, class_="form-control")}}
						</div>

						<div class="form-group">
							{{render_field(form.description, class_="form-control")}}
						</div>
						<div class="form-group">
							<label>Status</label>
							<select class="form-control" name="status">
							  <option value="" disabled selected>Select your option</option>	
							  <option value="unpaid">Unpaid</option>
							  <option value="paid">Paid</option>
							  <option value="pending">Pending</option>
							</select>							
						</div>
						<input type="submit" class="btn btn-success" value="submit">			
					</div>	
							
	{% endblock %}

	{% block right_nav %}
	<div class="col-sm-2">
					<div class="w3-container w3-teal">			
					<h3>Split with</h3>
					</div>
					<table class="w3-table-all w3-card">
					  <thead>
					    <tr>
					      <th>Person</th>
					      <th>Include</th>
					    </tr>
					  </thead>
					  <tbody>
					 	{% for item in data %}
					   <tr>
							 <td for="{{ item.user_id }}" id="selectBox" onchange="changeFunc();">{{ item.name }}</td>
					     <td><input type="checkbox" id="checkbox" name="person" value="{{ item.user_id }}"></td>
					    {% endfor %}	
					  </tr>
					  </tbody>
					  <b id="checkalert"></b>
					</table>

			</form>		
		</div>	
		{% endblock %}

	<script type="text/javascript">

		function changeFunc() {
		 var selectBox = document.getElementById("selectBox");
		 var selectedValue = selectBox.options[selectBox.selectedIndex].value;
		 alert(selectedValue);
		}
	 </script>

	<!-- <footer class="py-5 bg-dark">
	      <p class="m-0 text-center text-white">Copyright &copy; MankatoExpenses 2017</p>
	    /.container
	 </footer> -->

it680vizapp/site/templates/site/transaction_form_bak1.html
{% extends 'site/layout.html' %}

{% block body %}
	<script src="{{ url_for('site.static', filename='js/main.js') }}"></script>
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	<h1>New Transaction</h1>
	{% from "site/includes/_formhelpers.html" import render_field %}
	

	<form method="POST" action="" >
		<div class="col-sm-9">
			<div class="form-group">
				{{render_field(form.item, class_="form-control")}}
			</div>
			<div class="form-group">
				{{render_field(form.payer, class_="form-control")}}
			</div>
			<div class="form-group">
				{{render_field(form.amount, class_="form-control")}}
			</div>

			<div class="form-group">
				{{render_field(form.comment, class_="form-control")}}
			</div>
			<div class="form-group">
				{{render_field(form.status, class_="form-control")}}
			</div>
			
		</div>

		<div class="col-sm-3">
		    {% for item in data %}
		    <p for="{{ item.username }}">  
		    <input type="checkbox" value="{{ item.user_id }}" >{{ item.name }}<p>
		    {% endfor %}	
			<br>
			<div id="cbResults"></div>
		</div>
	 	
	</form>
	<input type="button" value="Submit" class="btn btn-primary">
	{% endblock %}
	
	

	

it680vizapp/site/templates/site/user_trans_view.html
{% extends 'site/layout.html' %}

{% block body %}
<form method="POST" action="">
  <div class="row">
  <div class="form-group">
      <div class="col-sm-7">
          <input type="text" placeholder="status" name="status", class="form-control">
      </div>
  
  <div class="form-group">
      <div class="col-sm-2">
          <input type="submit" value="SEARCH" class="btn btn-primary btn-block">
      </div>
      </div>
  </form>
  </div>

<div class="row"></div>
<br/>

  <div class="row">
    <div class="col-sm-7">
    	<table class="table table-bordered">
    	  <thead>
    	    <tr>
    	      <th>Date</th>
    	      <th>Item</th>
    	      <th>Num of People</th>
    	      <th>Payer</th>
    	      <th>Amount</th>
    	    </tr>
    	  </thead>
    	  <tbody>
    	  	{% for i in data_2 %}
    	    <tr>
    	      <td>{{i.entry_date}}</td>
    	      <td>{{i.item}}</td>
    	      <td>{{i.user_count}}</td>
    	      <td>{{i.payer}}</td>
    	      <td>${{i.shr_amount}}</td>
    	    </tr>
    	    {% endfor %}

    	  </tbody>
    	</table>
    </div>


	<div class="col-sm-5">
       <table class="table table-bordered">
         <thead>
           <tr>
           	 <th>User ID</th>
             <th>Name</th>
             <th>Own Share</th>               
             <th>Amount Lent</th>
           </tr>
         </thead>
         <tbody>
         	{% for item in data_4 %}
           <tr>
           	 <td>{{item.user_id}}</td>
             <td>{{item.name}}</td>
             <td>${{item.per_share}}</td>
             <td>${{item.amt_lent}}</td>
            </tr>
           {% endfor %}         
         </tbody>
       
         <!-- <thead>
           <tr>
             <th></th>
             <th>Total</th>
             <th>Amount</th>
             <th>Own_share</th>               
             <th>Lent</th>
           </tr>
         </thead> -->
      </table>

       <table class="table table-bordered">
         <thead>
           <tr>
             <th>Name</th>
             <th>Total Paid</th>
           </tr>
         </thead>
         <tbody>
          {% for item in data_3 %}
           <tr>
             <td>{{item.payer}}</td>
             <td>${{item.amount}}</td>
           {% endfor %}
         </tr>
         </tbody>
      </table>

    </div>
<div>
{% endblock %}

it680vizapp/site/templates/site/viz.html
{% extends 'site/layout.html' %}

{% block body %}

<div class="col-sm-2 sidenav">
		{% include 'site/includes/_vnavbar.html' %}
</div>

<div class="col-sm-8 text-left"> 
<div id="pieChart"></div>
<div id="barChart"></div>  
<div id="linechart"></div>  
</div>


<script>  dsPieChart();
          dsBarChart1();
          
</script>
<script src="http://dimplejs.org/dist/dimple.v2.3.0.min.js"></script>
{% endblock %}

{% block right_nav %}

{% endblock %}